# Default values for rabbitmq-sample.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: theryanbaker/ryantest
  tag: latest
  pullPolicy: IfNotPresent
